# I. $LU$ factorization of a square matrix
When we premultply $A$ by lower triangular elemetary matrices $\Lambda_j$ it is trasfrommed in an  upper triangular matrix $U$

$$  \Lambda_{n-1}  \ldots\Lambda_2  \Lambda_1 A  = U$$

$$  A  = (\Lambda_{n-1}  \ldots\Lambda_2  \Lambda_2 )^{-1} U$$

The inverse of a product of matrices is the revesre product of inverses
$$  A  = (\Lambda_1^{-1}  \Lambda_2^{-1} \ldots  \Lambda_{n-1}^{-1}) U$$

and inverse of a Lower Triangular Elemetary Matrix is minus the matrix $\Lambda_j^{-1} = - \Lambda_j$, so

$$ A  =  (-\Lambda_1) (-\Lambda_2) \ldots   (-\Lambda_{n-1})  U$$

So the $LU$ column pivot factorization is
$$  A  = L U$$
with
$$ U = \Lambda_{n-1}  \ldots\Lambda_2  \Lambda_1 A  $$
an upper triangular matrix
$$ L  =  \Lambda_1^{-1}  \Lambda_2^{-1} \ldots  \Lambda_{n-1}^{-1} m = (-\Lambda_1) (-\Lambda_2) \ldots   (-\Lambda_{n-1})  $$
an lower triangular matrix.

Consider a simple naive implementation of the LU decomposition.

Note that we're using the `numpy` arrays to represent matrices [do **not** use `np.matrix`].

In [1]:
import numpy as np

def diy_lu(a):
    N = a.shape[0]
    u = a.copy()
    L = np.eye(N)
    for j in range(N-1):
        # Create lower triangular elementary matrix
        lam = np.eye(N)
        # Compute multipliers for current column
        gamma = u[j+1:, j] / u[j, j]
        # Fill in sub-diagonal elements for elimination
        lam[j+1:, j] = -gamma
        # Apply elimination: premultiply U by lam
        u = lam @ u
        # For L, add the positive multipliers
        lam[j+1:, j] = gamma
        # Accumulate L
        L = L @ lam
    return L, u

# Example usage:
if __name__ == "__main__":
    A = np.array([[2., 1., 1.],
                  [4., -6., 0.],
                  [-2., 7., 2.]])
    L, U = diy_lu(A)
    print("L:\n", L)
    print("U:\n", U)
    print("L @ U:\n", L @ U)

L:
 [[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1. -1.  1.]]
U:
 [[ 2.  1.  1.]
 [ 0. -8. -2.]
 [ 0.  0.  1.]]
L @ U:
 [[ 2.  1.  1.]
 [ 4. -6.  0.]
 [-2.  7.  2.]]


In [2]:
import numpy as np

def diy_lu(a):
    N = a.shape[0]
    u = a.copy()
    L = np.eye(N)
    for j in range(N-1):
        lam = np.eye(N)
        gamma = u[j+1:, j] / u[j, j]
        lam[j+1:, j] = -gamma
        u = lam @ u
        lam[j+1:, j] = gamma
        L = L @ lam
    return L, u


N = 6
A = np.zeros((N, N), dtype=float)
for i in range(N):
    for j in range(N):
        A[i, j] = 3. / (0.6*i*j + 1)

# Check the rank
print("Rank of A:", np.linalg.matrix_rank(A))

# Test LU decomposition
L, U = diy_lu(A)

# Check if L @ U == A
print("Is L @ U close to A?", np.allclose(L @ U, A))


print("L:\n", L)
print("U:\n", U)

Rank of A: 6
Is L @ U close to A? True
L:
 [[1.         0.         0.         0.         0.         0.        ]
 [1.         1.         0.         0.         0.         0.        ]
 [1.         1.45454545 1.         0.         0.         0.        ]
 [1.         1.71428571 1.74223602 1.         0.         0.        ]
 [1.         1.88235294 2.27586207 2.03908376 1.         0.        ]
 [1.         2.         2.67142857 2.944      2.35448132 1.        ]]
U:
 [[ 3.00000000e+00  3.00000000e+00  3.00000000e+00  3.00000000e+00
   3.00000000e+00  3.00000000e+00]
 [ 0.00000000e+00 -1.12500000e+00 -1.63636364e+00 -1.92857143e+00
  -2.11764706e+00 -2.25000000e+00]
 [ 0.00000000e+00  0.00000000e+00  2.62518230e-01  4.57368718e-01
   5.97455283e-01  7.01298701e-01]
 [ 0.00000000e+00  2.22044605e-16  0.00000000e+00 -2.19718086e-02
  -4.48023580e-02 -6.46850044e-02]
 [ 0.00000000e+00 -4.52767547e-16  0.00000000e+00  6.93889390e-18
   8.07981372e-04  1.90237705e-03]
 [ 0.00000000e+00  4.12333415e-16

In [3]:
np.round(A,3)

array([[3.   , 3.   , 3.   , 3.   , 3.   , 3.   ],
       [3.   , 1.875, 1.364, 1.071, 0.882, 0.75 ],
       [3.   , 1.364, 0.882, 0.652, 0.517, 0.429],
       [3.   , 1.071, 0.652, 0.469, 0.366, 0.3  ],
       [3.   , 0.882, 0.517, 0.366, 0.283, 0.231],
       [3.   , 0.75 , 0.429, 0.3  , 0.231, 0.188]])

In [4]:
L, U = diy_lu(A)

print(np.round(L,3), "\n")
print(np.round(U,3), "\n")

# Quick sanity check: L times U must equal the original matrix, up to floating-point errors.
print(np.round(L@U - A,3))

[[1.    0.    0.    0.    0.    0.   ]
 [1.    1.    0.    0.    0.    0.   ]
 [1.    1.455 1.    0.    0.    0.   ]
 [1.    1.714 1.742 1.    0.    0.   ]
 [1.    1.882 2.276 2.039 1.    0.   ]
 [1.    2.    2.671 2.944 2.354 1.   ]] 

[[ 3.000e+00  3.000e+00  3.000e+00  3.000e+00  3.000e+00  3.000e+00]
 [ 0.000e+00 -1.125e+00 -1.636e+00 -1.929e+00 -2.118e+00 -2.250e+00]
 [ 0.000e+00  0.000e+00  2.630e-01  4.570e-01  5.970e-01  7.010e-01]
 [ 0.000e+00  0.000e+00  0.000e+00 -2.200e-02 -4.500e-02 -6.500e-02]
 [ 0.000e+00 -0.000e+00  0.000e+00  0.000e+00  1.000e-03  2.000e-03]
 [ 0.000e+00  0.000e+00  0.000e+00 -0.000e+00  0.000e+00 -0.000e+00]] 

[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0. -0.  0.  0. -0.]
 [ 0.  0.  0. -0. -0.  0.]
 [ 0.  0.  0. -0. -0.  0.]
 [ 0.  0. -0. -0.  0.  0.]]


# II. The need for pivoting

Let's tweak the matrix a little bit, we only change a single element:

In [5]:
A1 = A.copy()
A1[1, 1] = 3

In [6]:
np.round(A1,3)

array([[3.   , 3.   , 3.   , 3.   , 3.   , 3.   ],
       [3.   , 3.   , 1.364, 1.071, 0.882, 0.75 ],
       [3.   , 1.364, 0.882, 0.652, 0.517, 0.429],
       [3.   , 1.071, 0.652, 0.469, 0.366, 0.3  ],
       [3.   , 0.882, 0.517, 0.366, 0.283, 0.231],
       [3.   , 0.75 , 0.429, 0.3  , 0.231, 0.188]])

In [7]:
np.linalg.matrix_rank(A1)

np.int64(6)

In [8]:
L, U= diy_lu(A1)

print(L, U)

[[nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]] [[nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]]


/tmp/ipython-input-2-1848805866.py:15: RuntimeWarning: divide by zero encountered in divide
  gamma = u[j+1:, j] / u[j, j]
/tmp/ipython-input-2-1848805866.py:17: RuntimeWarning: invalid value encountered in matmul
  u = lam @ u
/tmp/ipython-input-2-1848805866.py:19: RuntimeWarning: invalid value encountered in matmul
  L = L @ lam
/tmp/ipython-input-2-1848805866.py:15: RuntimeWarning: invalid value encountered in divide
  gamma = u[j+1:, j] / u[j, j]


The LU decomposition from scipy.linalg.lu already implements pivoting other sophisticated controls

https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lu.html

$$A = P L U$$

```python

 P ,  L,  U  = scipy.linalg.lu(a, permute_l=False, overwrite_a=False, check_finite=True)

# Returns
# (If permute_l == False)
# P : Permutation matrix
# L : Lower triangular or trapezoidal matrix with unit diagonal. K = min
# U : Upper triangular or trapezoidal matrix
```

In [9]:
from scipy import linalg
P ,  L,  U = linalg.lu(A)

print("P\n",P, "\n")
print("L\n",L, "\n")
print("U\n",np.round(U,3), "\n")
print("A= P@L@U\n", P@L@U, "\n")
print("A\n",A, "\n")


P
 [[1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]] 

L
 [[1.         0.         0.         0.         0.         0.        ]
 [1.         1.         0.         0.         0.         0.        ]
 [1.         0.5        1.         0.         0.         0.        ]
 [1.         0.72727273 0.70588235 1.         0.         0.        ]
 [1.         0.85714286 0.40993789 0.83482143 1.         0.        ]
 [1.         0.94117647 0.17849899 0.4255677  0.78870221 1.        ]] 

U
 [[ 3.000e+00  3.000e+00  3.000e+00  3.000e+00  3.000e+00  3.000e+00]
 [ 0.000e+00 -2.250e+00 -2.571e+00 -2.700e+00 -2.769e+00 -2.812e+00]
 [ 0.000e+00  0.000e+00 -3.510e-01 -5.790e-01 -7.330e-01 -8.440e-01]
 [ 0.000e+00  0.000e+00  0.000e+00  2.400e-02  4.900e-02  7.000e-02]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00 -1.000e-03 -2.000e-03]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]] 

A= P@L@U
 [[3.         3.   

In [10]:
P ,  L,  U = linalg.lu(A1)

print("P\n",P, "\n")
print("L\n",L, "\n")
print("U\n",np.round(U,3), "\n")
print("A= P@L@U\n", P@L@U, "\n")
print("A\n",A, "\n")


P
 [[1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]] 

L
 [[ 1.          0.          0.          0.          0.          0.        ]
 [ 1.          1.          0.          0.          0.          0.        ]
 [ 1.         -0.          1.          0.          0.          0.        ]
 [ 1.          0.72727273  0.1512605   1.          0.          0.        ]
 [ 1.          0.85714286  0.08784383  0.51421669  1.          0.        ]
 [ 1.          0.94117647  0.03824978  0.2076544   0.64143198  1.        ]] 

U
 [[ 3.000e+00  3.000e+00  3.000e+00  3.000e+00  3.000e+00  3.000e+00]
 [ 0.000e+00 -2.250e+00 -2.571e+00 -2.700e+00 -2.769e+00 -2.812e+00]
 [ 0.000e+00  0.000e+00 -1.636e+00 -1.929e+00 -2.118e+00 -2.250e+00]
 [ 0.000e+00  0.000e+00  0.000e+00 -9.200e-02 -1.480e-01 -1.860e-01]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  2.000e-03  4.000e-03]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00 -0.000e

### Test II.1

For a naive LU decomposition to work, all leading minors of a matrix should be non-zero. Check if this requirement is satisfied for the two matrices `a` and `a1`.

(20% of the grade)

In [11]:
import numpy as np

def leading_minors_test(A):
    N = A.shape[0]
    for k in range(1, N+1):
        minor = A[:k, :k]
        if np.linalg.det(minor) == 0:
            return False
    return True

print(leading_minors_test(A), leading_minors_test(A1))

True False


### Test II.2

Modify the `diy_lu` routine to implement column pivoting. Keep track of pivots, you can either construct a permutation matrix, or a swap array (your choice).

(40% of the grade)

Implement a function to reconstruct the original matrix from a decompositon. Test your routines on the matrices `a` and `a1`.

(40% of the grade)

In [12]:
import numpy as np

def diy_lu_pivot(a):
    N = a.shape[0]
    u = a.copy()
    L = np.eye(N)
    swap_array = np.arange(N)

    for j in range(N-1):
        # Find column with largest absolute value in u[j, j:]
        col_max = np.argmax(np.abs(u[j, j:])) + j
        if col_max != j:
            u[:, [j, col_max]] = u[:, [col_max, j]]
            swap_array[[j, col_max]] = swap_array[[col_max, j]]
            if j > 0:
                L[:j, [j, col_max]] = L[:j, [col_max, j]]

        lam = np.eye(N)
        gamma = u[j+1:, j] / u[j, j]
        lam[j+1:, j] = -gamma
        u = lam @ u
        lam[j+1:, j] = gamma
        L = L @ lam

    return L, u, swap_array


if __name__ == "__main__":
    N = 6
    A = np.zeros((N, N), dtype=float)
    for i in range(N):
        for j in range(N):
            A[i, j] = 3. / (0.6*i*j + 1)

    L, U, swap_array = diy_lu_pivot(A)
    print("L:\n", L)
    print("U:\n", U)
    print("swap_array:", swap_array)

    print("L @ U:\n", L @ U)
    print("A[:, swap_array]:\n", A[:, swap_array])
    print("Is L @ U close to permuted A?", np.allclose(L @ U, A[:, swap_array]))

L:
 [[1.         0.         0.         0.         0.         0.        ]
 [1.         1.         0.         0.         0.         0.        ]
 [1.         1.14285714 1.         0.         0.         0.        ]
 [1.         1.2        1.65       1.         0.         0.        ]
 [1.         1.23076923 2.09049774 2.0096739  1.         0.        ]
 [1.         1.25       2.40625    2.875      2.34615179 1.        ]]
U:
 [[ 3.00000000e+00  3.00000000e+00  3.00000000e+00  3.00000000e+00
   3.00000000e+00  3.00000000e+00]
 [ 0.00000000e+00 -2.25000000e+00 -1.12500000e+00 -1.63636364e+00
  -1.92857143e+00 -2.11764706e+00]
 [ 0.00000000e+00  0.00000000e+00 -3.50649351e-01 -2.47517189e-01
  -1.43744454e-01 -6.25905535e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  2.42136380e-02
   2.02140639e-02  1.03045423e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -6.93889390e-18
  -6.46187856e-04 -5.09649789e-04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.62796983e-17
   2.1

In [13]:
import numpy as np

def diy_lu(a):
    N = a.shape[0]
    u = a.copy()
    L = np.eye(N)
    for j in range(N-1):
        lam = np.eye(N)
        gamma = u[j+1:, j] / u[j, j]
        lam[j+1:, j] = -gamma
        u = lam @ u
        lam[j+1:, j] = gamma
        L = L @ lam
    return L, u

def diy_lu_column_pivot_reconstruct(A):
    N = A.shape[0]
    U = A.copy()
    L = np.eye(N)
    P_total = np.eye(N)

    for j in range(N-1):
        col_max = np.argmax(np.abs(U[j, j:])) + j

        # Construct permutation matrix for current step
        Pj = np.eye(N)
        if col_max != j:
            Pj[:, [j, col_max]] = Pj[:, [col_max, j]]
            U[:, [j, col_max]] = U[:, [col_max, j]]

        # Elimination (lower triangular elementary matrix)
        lam = np.eye(N)
        gamma = U[j+1:, j] / U[j, j]
        lam[j+1:, j] = -gamma
        U = lam @ U

        # For L: accumulate as Pt_j @ lam @ L
        lam[j+1:, j] = gamma
        L = Pj.T @ lam @ L

        # Accumulate total permutation
        P_total = Pj @ P_total

    return P_total, L, U

def reconstruct_from_lu(L, U, swap_array=None, P=None):

    if swap_array is not None:
        inverse_swap = np.argsort(swap_array)
        return (L @ U)[:, inverse_swap]
    elif P is not None:
        return np.linalg.inv(P) @ (L @ U)
    else:
        return L @ U

if __name__ == "__main__":
    N = 6
    a = np.zeros((N, N), dtype=float)
    for i in range(N):
        for j in range(N):
            a[i, j] = 3. / (0.6*i*j + 1)
    a1 = np.random.rand(N, N)

    # LU decomposition without pivoting
    L, U = diy_lu(a)
    A_rec = reconstruct_from_lu(L, U)
    print("Reconstruction error (a, naive):", np.linalg.norm(a - A_rec))

    L1, U1 = diy_lu(a1)
    A1_rec = reconstruct_from_lu(L1, U1)
    print("Reconstruction error (a1, naive):", np.linalg.norm(a1 - A1_rec))

    # LU decomposition with column pivoting using permutation matrix
    P, Lp, Up = diy_lu_column_pivot_reconstruct(a)
    Ap_rec = reconstruct_from_lu(Lp, Up, P=P)
    print("Column pivot reconstruction error (a):", np.linalg.norm(a - Ap_rec))

    P1, Lp1, Up1 = diy_lu_column_pivot_reconstruct(a1)
    Ap1_rec = reconstruct_from_lu(Lp1, Up1, P=P1)
    print("Column pivot reconstruction error (a1):", np.linalg.norm(a1 - Ap1_rec))

Reconstruction error (a, naive): 5.978733960281817e-16
Reconstruction error (a1, naive): 8.951979947807797e-16
Column pivot reconstruction error (a): 292.4585684912843
Column pivot reconstruction error (a1): 10.022081484699099


# 2. $LU$ factorization column pivoting and reconstruction
When we premultply $A$ by elementary permutation matricex$P_j$( to find a good pivot) and then premultply by lower triangular elemetary matrices $\Lambda_j$, $A$  it is transformed in an  upper triangular matrix $U$

$$  
(\Lambda_{n-1} P_{n-1} \ldots \Lambda_2 P_2 \Lambda_1 P_1)A  = U
$$
and
$$  
A  = (\Lambda_{n-1} P_{n-1} \ldots \Lambda_2 P_2 \Lambda_1 P_1)^{-1} U
$$


So the $LU$ column pivot factorization of $A$ is
$$
A = LU
$$
ith
$$  
U = (\Lambda_{n-1} P_{n-1} \ldots \Lambda_2 P_2 \Lambda_1 P_1) A
$$
$$
\begin{array}{ll}L  &=  (\Lambda_{n-1} P_{n-1} \ldots \Lambda_2 P_2 \Lambda_1 P_1)^{-1}\\
&= P_1^{-1} \Lambda_1^{-1} P_2^{-1} \Lambda_2^{-1} \ldots  P_{n-1}^{-1}\\
 &= P_1^{t} (-\Lambda_1) P_2^{t} (-\Lambda_2) \ldots  P_{n-1}^{t} (-\Lambda_{n-1})
\end{array}
$$
because the inverse a of a Lower Triangular Elemetary Matrix is minus the matrix $\Lambda_i^{-1} = - \Lambda_i$ and the inverse of a Permutation Matrix (in particular an elementary permutation matrix)  is its transpose [math.stackexchange](
        https://math.stackexchange.com/questions/98549/the-transpose-of-a-permutation-matrix-is-its-inverse#:~:text=Taking%20the%20transpose%20of%20P,Pt%3DP%E2%88%921.)  $P_i^{-1}=P_i^{t}$.

Note that
$$
L= P_1^{t} (-\Lambda_1) P_2^{t} (-\Lambda_2) \ldots  P_{n-1}^{t} (-\Lambda_{n-1})
$$
is not exactly a lower tiangular matrix but a row permutated lower tiangular matrix.





$$PA = LU$$

In [14]:
import numpy as np

def diy_lu(a):
    N = a.shape[0]
    u = a.copy()
    L = np.eye(N)
    for j in range(N-1):
        lam = np.eye(N)
        gamma = u[j+1:, j] / u[j, j]
        lam[j+1:, j] = -gamma
        u = lam @ u
        lam[j+1:, j] = gamma
        L = L @ lam
    return L, u

def diy_lu_pivot(a):
    N = a.shape[0]
    u = a.copy()
    L = np.eye(N)
    swap_array = np.arange(N)
    for j in range(N-1):
        col_max = np.argmax(np.abs(u[j, j:])) + j
        if col_max != j:
            u[:, [j, col_max]] = u[:, [col_max, j]]
            swap_array[[j, col_max]] = swap_array[[col_max, j]]
            if j > 0:
                L[:j, [j, col_max]] = L[:j, [col_max, j]]
        lam = np.eye(N)
        gamma = u[j+1:, j] / u[j, j]
        lam[j+1:, j] = -gamma
        u = lam @ u
        lam[j+1:, j] = gamma
        L = L @ lam
    return L, u, swap_array

def reconstruct_from_lu(L, U, swap_array=None):
    A_reconstructed = L @ U
    if swap_array is not None:
        inverse_swap = np.argsort(swap_array)
        A_reconstructed = A_reconstructed[:, inverse_swap]
    return A_reconstructed

if __name__ == "__main__":
    N = 6
    a = np.zeros((N, N), dtype=float)
    for i in range(N):
        for j in range(N):
            a[i, j] = 3. / (0.6*i*j + 1)
    a1 = np.random.rand(N, N)

    # LU decomposition without pivoting
    L, U = diy_lu(a)
    A_rec = reconstruct_from_lu(L, U)
    print("Reconstruction error (a):", np.linalg.norm(a - A_rec))

    L1, U1 = diy_lu(a1)
    A1_rec = reconstruct_from_lu(L1, U1)
    print("Reconstruction error (a1):", np.linalg.norm(a1 - A1_rec))

    # LU decomposition with column pivoting
    Lp, Up, swap_array = diy_lu_pivot(a)
    Ap_rec = reconstruct_from_lu(Lp, Up, swap_array)
    print("Pivoted reconstruction error (a):", np.linalg.norm(a - Ap_rec))

    Lp1, Up1, swap_array1 = diy_lu_pivot(a1)
    Ap1_rec = reconstruct_from_lu(Lp1, Up1, swap_array1)
    print("Pivoted reconstruction error (a1):", np.linalg.norm(a1 - Ap1_rec))

Reconstruction error (a): 5.978733960281817e-16
Reconstruction error (a1): 1.4464889531490702e-15
Pivoted reconstruction error (a): 9.408280408450705e-16
Pivoted reconstruction error (a1): 3.002232803159773e-16


In [15]:
A = np.array([[4,3,1], [5,7,0], [9,9,3]])

P, L, U, = diy_lu_column_pivot_reconstruct(A)

print("P\n",P, "\n")
print("L\n",L, "\n")
print("U\n",U, "\n")
print("A= P@L@U\n", P@L@U, "\n")
print("A\n",A, "\n")

# Quick sanity check: L times U must equal the original matrix, up to floating-point errors.
print("L@u - A\n",np.round(P@L@U-A,3), "\n")

P
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

L
 [[1.         0.         0.        ]
 [1.25       1.         0.        ]
 [3.11538462 0.69230769 1.        ]] 

U
 [[ 4.          3.          1.        ]
 [ 0.          3.25       -1.25      ]
 [ 0.          0.          1.61538462]] 

A= P@L@U
 [[ 4.          3.          1.        ]
 [ 5.          7.          0.        ]
 [12.46153846 11.59615385  3.86538462]] 

A
 [[4 3 1]
 [5 7 0]
 [9 9 3]] 

L@u - A
 [[0.    0.    0.   ]
 [0.    0.    0.   ]
 [3.462 2.596 0.865]] 



In [16]:
from scipy import linalg

A = np.array([[4,3,1], [5,7,0], [9,9,3]])

P,L,U = linalg.lu(A)

print("P\n",P, "\n")
print("L\n",L, "\n")
print("U\n",U, "\n")
print("A= P@L@U\n", P@L@U, "\n")
print("A\n",A, "\n")

# Quick sanity check: L times U must equal the original matrix, up to floating-point errors.
print("L@u - A\n",np.round(P@L@U-A,3), "\n")

P
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]] 

L
 [[ 1.          0.          0.        ]
 [ 0.55555556  1.          0.        ]
 [ 0.44444444 -0.5         1.        ]] 

U
 [[ 9.          9.          3.        ]
 [ 0.          2.         -1.66666667]
 [ 0.          0.         -1.16666667]] 

A= P@L@U
 [[4. 3. 1.]
 [5. 7. 0.]
 [9. 9. 3.]] 

A
 [[4 3 1]
 [5 7 0]
 [9 9 3]] 

L@u - A
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 



In [17]:
N = 6
A = np.zeros((N, N), dtype=float)
for i in range(N):
    for j in range(N):
        A[i, j] = 3. / (0.6*i*j + 1)

P, L, U, = diy_lu_column_pivot_reconstruct(A)

print("P\n",P, "\n")
print("L\n",L, "\n")
print("U\n",U, "\n")
print("A= P@L@U\n", P@L@U, "\n")
print("A\n",A, "\n")

# Quick sanity check: L times U must equal the original matrix, up to floating-point errors.
print("L@u - A\n",np.round(P@L@U-A,3), "\n")




P
 [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]] 

L
 [[ 1.          0.          0.          0.          0.          0.        ]
 [ 2.25        1.25        0.          0.          0.          1.        ]
 [ 6.15625     3.75        2.40625     0.          0.          0.        ]
 [18.63303571 10.01428571  5.74375     2.875       0.          0.        ]
 [48.52324107 26.12771429 14.334375    5.715       2.34615179  0.        ]
 [18.23732252  9.82118895  5.40645967  2.0096739   1.          0.        ]] 

U
 [[ 3.00000000e+00  3.00000000e+00  3.00000000e+00  3.00000000e+00
   3.00000000e+00  3.00000000e+00]
 [ 0.00000000e+00 -2.25000000e+00 -1.12500000e+00 -1.63636364e+00
  -1.92857143e+00 -2.11764706e+00]
 [ 0.00000000e+00  0.00000000e+00 -3.50649351e-01 -2.47517189e-01
  -1.43744454e-01 -6.25905535e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  2.42136380e-02
   2.02140639e-02  1.03045423e-02]
 [ 0.

In [18]:
from scipy import linalg

P,L,U = linalg.lu(A)

print("P\n",P, "\n")
print("L\n",L, "\n")
print("U\n",U, "\n")
print("A= P@L@U\n", P@L@U, "\n")
print("A\n",A, "\n")

# Quick sanity check: L times U must equal the original matrix, up to floating-point errors.
print("L@u - A\n",np.round(P@L@U-A,3), "\n")

P
 [[1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]] 

L
 [[1.         0.         0.         0.         0.         0.        ]
 [1.         1.         0.         0.         0.         0.        ]
 [1.         0.5        1.         0.         0.         0.        ]
 [1.         0.72727273 0.70588235 1.         0.         0.        ]
 [1.         0.85714286 0.40993789 0.83482143 1.         0.        ]
 [1.         0.94117647 0.17849899 0.4255677  0.78870221 1.        ]] 

U
 [[ 3.00000000e+00  3.00000000e+00  3.00000000e+00  3.00000000e+00
   3.00000000e+00  3.00000000e+00]
 [ 0.00000000e+00 -2.25000000e+00 -2.57142857e+00 -2.70000000e+00
  -2.76923077e+00 -2.81250000e+00]
 [ 0.00000000e+00  0.00000000e+00 -3.50649351e-01 -5.78571429e-01
  -7.33031674e-01 -8.43750000e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  2.42136380e-02
   4.86615163e-02  6.96142093e-02]
 [ 0.00000000e+00  0.00000000e+00  0.0000

In [19]:
A[1, 1] = 3

P, L, U, = diy_lu_column_pivot_reconstruct(A1)

print("P\n",P, "\n")
print("L\n",L, "\n")
print("U\n",U, "\n")
print("A= P@L@U\n", P@L@U, "\n")
print("A\n",A, "\n")

# Quick sanity check: L times U must equal the original matrix, up to floating-point errors.
print("L@u - A\n",np.round(P@L@U-A,3), "\n")

P
 [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]] 

L
 [[ 1.          0.          0.          0.          0.          0.        ]
 [ 2.25        1.25        0.          0.          0.          1.        ]
 [ 3.94642857  2.57142857  1.375       0.          0.          0.        ]
 [11.6292305   6.2557891   3.3659601   2.0074813   0.          0.        ]
 [30.8573823  16.65794538  7.79174587  4.33212095  2.0755701   0.        ]
 [12.59021418  6.79861721  3.18619662  1.60540034  1.          0.        ]] 

U
 [[ 3.00000000e+00  3.00000000e+00  3.00000000e+00  3.00000000e+00
   3.00000000e+00  3.00000000e+00]
 [ 0.00000000e+00 -2.25000000e+00  0.00000000e+00 -1.63636364e+00
  -1.92857143e+00 -2.11764706e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.63636364e+00 -2.47517189e-01
  -1.43744454e-01 -6.25905535e-02]
 [ 0.00000000e+00  0.00000000e+00  2.22044605e-16 -9.24730366e-02
  -4.75511789e-02 -1.92024329e-02]
 [ 0.

In [20]:
from scipy import linalg

P,L,U = linalg.lu(A)

print("P\n",P, "\n")
print("L\n",L, "\n")
print("U\n",U, "\n")
print("A= P@L@U\n", P@L@U, "\n")
print("A\n",A, "\n")

# Quick sanity check: L times U must equal the original matrix, up to floating-point errors.
print("L@u - A\n",np.round(P@L@U-A,3), "\n")

P
 [[1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]] 

L
 [[ 1.          0.          0.          0.          0.          0.        ]
 [ 1.          1.          0.          0.          0.          0.        ]
 [ 1.         -0.          1.          0.          0.          0.        ]
 [ 1.          0.72727273  0.1512605   1.          0.          0.        ]
 [ 1.          0.85714286  0.08784383  0.51421669  1.          0.        ]
 [ 1.          0.94117647  0.03824978  0.2076544   0.64143198  1.        ]] 

U
 [[ 3.00000000e+00  3.00000000e+00  3.00000000e+00  3.00000000e+00
   3.00000000e+00  3.00000000e+00]
 [ 0.00000000e+00 -2.25000000e+00 -2.57142857e+00 -2.70000000e+00
  -2.76923077e+00 -2.81250000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.63636364e+00 -1.92857143e+00
  -2.11764706e+00 -2.25000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -9.24730366e-02
  -1.48456245e-01 -1.85637892e-01]
 [ 0.